### ISSUE TITLE
データ投入 Seed Users関連

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#12]
db/seeds.rb にUserの仮データを入れること

2人のユーザーを作成すること。Email, Passwordは今後何度も使用するため、覚えやすいシンプルなものにすること。
UserClassificationオブジェクトは1種類でOK

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で User.all を実行 → User一覧が出てくる。これをスクショして添付すること。

**Comment by e-kaneyuki** [comment]
お疲れ様です。
Seedファイル作成し、Userを作成してみました.
ご確認お願いいたします。

<img width="1440" alt="スクリーンショット 2021-08-13 18 27 15" src="https://user-images.githubusercontent.com/69076028/129336593-ad2cba44-ba10-4db5-9900-6baaf0a09311.png">

**Comment by yuki-tachi0219** [comment]
よさそうなのえ、そのままプルリクお願いします！

**Comment by yuki-tachi0219** [comment]
直したいところはいくつかありますが、プルリク上でお伝えします。
