### ISSUE TITLE
データ投入 Seed Products関連

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#13]
db/seeds.rb にProduct関係の仮データを入れること

2人のユーザーに対して2つずつProductを作成すること。
seedを実行することで、合計4つのProductが生成されるようにすること。

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショして添付すること。

**Comment by naokinoid** [comment]
@yuki-tachi0219 
仮データ作成しました。
ご確認をお願いいたします。

一応、Category.all、SaleStatus.all、ProductStatus.allの結果も添付いたします。

<img width="838" alt="スクリーンショット 2021-08-11 16 33 08" src="https://user-images.githubusercontent.com/66786623/128989477-9ecd960c-0fb5-494b-a892-57b063f75882.png">
<img width="834" alt="スクリーンショット 2021-08-11 16 37 47" src="https://user-images.githubusercontent.com/66786623/128989522-9827f25d-98af-44db-8ddf-fab4ea1a809e.png">
<img width="832" alt="スクリーンショット 2021-08-11 16 38 18" src="https://user-images.githubusercontent.com/66786623/128989563-2325350f-35f6-4931-bcd8-ef5f1c69559c.png">
<img width="830" alt="スクリーンショット 2021-08-11 16 38 38" src="https://user-images.githubusercontent.com/66786623/128989580-0e6d9c7b-6fc1-4468-8eb9-07a7f7904dc8.png">

**Comment by yuki-tachi0219** [comment]
ご報告ありがとうございます。
問題なさそうなので、そのままプルリクをしていただければと思います。
user_id:1がアウトドア好きで、user_id:2が筋トレ好きなんですね ✨
