### ISSUE TITLE
ユーザー情報画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#17]
path: /users/:id
controller#action: Users#show
参考モックアップ: users_show.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by naokinoid** [comment]
@yuki-tachi0219 

ユーザー情報画面作成の進め方、レビューをお願いできますでしょうか。

・users_controllerの作成（rails generate controller users）
・users_controllerに showメソッドを追加
・routeの追記（今後のことを考え、resources :users）
・app/views/usersディレクトリに show.html.erbファイルを作成
　モックアップのhtmlのデータを移植、userデータが表示されるように変更

**Comment by yuki-tachi0219** [comment]
OKです！このまま進めましょう！
>routeの追記（今後のことを考え、resources :users）

この配慮は素晴らしすぎます ✨

**Comment by naokinoid** [comment]
了解しました！これで進めます。
ありがとうございます！

**Comment by naokinoid** [comment]
@yuki-tachi0219 

スクリーンショット添付します。
ご確認お願いします。
<img width="1440" alt="スクリーンショット 2021-08-13 10 39 07" src="https://user-images.githubusercontent.com/66786623/129292779-9eb04f4f-d1bf-4a8f-a191-ddf057e7027a.png">

**Comment by yuki-tachi0219** [comment]
いい感じですね！
このままプルリクお願いします！
