### ISSUE TITLE
環境構築(宮川さん)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#2]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by miyagawadaiki515** [comment]
#2 環境構築

**Comment by miyagawadaiki515** [comment]
#2 環境構築
<img width="1166" alt="スクリーンショット 2021-08-05 15 23 54" src="https://user-images.githubusercontent.com/85547902/128312888-3129de43-2fe6-41a7-bbec-d72de4a577ab.png">

**Comment by miyagawadaiki515** [comment]
#2 環境構築
レビューをお願いします。
<img width="1166" alt="スクリーンショット 2021-08-05 15 23 54" src="https://user-images.githubusercontent.com/85547902/128313162-853ebc55-8088-4c1b-a62a-0638396482ff.png">

**Comment by yuki-tachi0219** [comment]
OKです！これで完了といたします！
