### ISSUE TITLE
商品詳細画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#22]
path: /products/:id
controller#action: Products#show
参考モックアップ: products_show.html, products_show_not_found.html

URLで指定したidを持つ商品がある場合は、その商品の情報を表示(products_show.html)
商品が存在しない場合は、「該当商品が見つかりませんでした」と表示(products_show_not_found.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuki-tachi0219** [comment]
- [ ] ルーティング設定
  -  Products#show
- [ ] コントローラーとアクションを定義
  - ProductsControllerのshowアクション
- [ ] モックアップからhtml.erbさくせい
  - [ ] products_show.html からパクる
  - [ ] インスタンス変数をhtml.erbに埋め込む
  - [ ] 静的なコード(名前、価格など)を動的に
