### ISSUE TITLE
ユーザー情報修正画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#23]
path: /users/:id/edit
controller#action: Users#edit
参考モックアップ: users_edit.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「修正」「退会」ボタンを押した後の機能は実装不要

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by e-kaneyuki** [comment]
- [ ] ローカルリポジトリにedit.html.erbを作成
- [ ] edit.html.erb にモックアップのデータを引用
- [ ] ルーティングの確認 (/users/:id/edit(.:format) )
- [ ] ローカルサーバーで、モックアップから引用したデータが表示されるかを確認
- [ ] ルーティングに対応するメソッドの作成
　　作成箇所はコントローラ#アクションで、今回はusers#editメソッド
- [ ] 修正ボタンを押すことで入力した修正データがアップデートできることを確認する

**Comment by yuki-tachi0219** [comment]
>修正ボタンを押すことで入力した修正データがアップデートできることを確認する

この作業はしなくて大丈夫です。別のissueでやる予定なので。


今回はユーザー情報を修正する画面の実装なので、idで指定したユーザーの情報が修正画面で表示されるようにしてください。
`/users/3/edit` でid: 3のユーザーの情報編集画面が表示されるような感じですね

**Comment by e-kaneyuki** [comment]
お疲れ様です
細分化したタスクは完了しました
確認お願い致します🙇‍♂️

<img width="1440" alt="スクリーンショット 2021-08-20 22 47 50" src="https://user-images.githubusercontent.com/69076028/130243189-0e5bbfc3-7369-4f79-acfe-7d0c8b099514.png">

**Comment by yuki-tachi0219** [comment]
見た目はいい感じですね！
上記id:2のユーザー情報が自動的に入ればいいですね！

**Comment by e-kaneyuki** [comment]
お疲れ様です
入力フォームにユーザー情報を反映させることができました。
確認お願い致します🙇‍♂️

ただ、郵便番号や電話番号の間にハイフンを入れるpatternが実装できず苦戦しています。
アドバイス頂ければ幸いです。

<img width="1440" alt="スクリーンショット 2021-08-22 20 16 55" src="https://user-images.githubusercontent.com/69076028/130353301-3ed55165-3c9a-4242-9f16-e0766d479e64.png">

**Comment by yuki-tachi0219** [comment]
>郵便番号や電話番号の間にハイフンを入れるpatternが実装できず苦戦しています。

データベースに`2773315`というデータがあって、それを`277-3315`に変換した上でこのフォームに表示させたいということでしょうか。それならやる必要ないですよ
