### ISSUE TITLE
ユーザー情報更新

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#26]
アクション：Users#update
更新処理に成功したら ユーザー情報画面へ遷移、更新処理に失敗したら情報修正画面に戻り、エラーメッセージを表示させること

参考
- https://pikawaka.com/rails/update
- https://railstutorial.jp/chapters/updating_and_deleting_users?version=5.1#sec-updating_users

**Comment by e-kaneyuki** [comment]
- users_controller のupdateメソッド作成
  - 条件分岐　
    - 成功パターン
      - user詳細画面へ戻る
      - flashメッセージで"更新に成功しました"を表示させる
    - 失敗パターン
      - user情報修正画面へ戻る
      - flashメッセージで"情報更新に失敗しました"を表示させる
  - ストロングパラーメータの作成 ※画面定義書を参考に実装
     - (userの情報の中で編集可能なものを指定)
       - user_classification_id: 以外は修正できるようにする
         - ```permit(:last_name, :first_name, :zipcode, :prefecture, :municipality, :address, :apartments, :email, :phone_number, :password)```

想定所要時間：6~8時間

**Comment by yuki-tachi0219** [comment]
ストロングパラメータのところ、`:password`だけでなく`:password_confirmation`も入れなきゃいけないかもしれないです。
試しに動かして検証してみてください。
