### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#27]
path: /login
controller#action: Sessions#new
参考モックアップ: sessions_new.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

画面が表示できたら、スクショを貼り付けること。
ログイン処理(ログインボタンを押したあとの処理)は実装不要

参考：https://qiita.com/d0ne1s/items/7c4d2be3f53e34a9dec7

**Comment by miyagawadaiki515** [comment]
#27 ログイン画面　チェックリスト
-[ ]user モデルの作成、カラムは name, email, password_digest
-[ ]ハッシュ化した password で認証ができるように設定
  - user モデルに has_secure_password  を追加
  - ダミーデータの作成
-[ ]session を利用してユーザーを判別する仕組みを作る
  - session_controller ,newアクションを作る
  - モックアップを参考に sessions_new.html ファイルの作成
  - ルーティングの設定 Sessions#new

画面が確認できることを確認する
想定時間：2時間

**Comment by yuki-tachi0219** [comment]
>user モデルに password_digest カラムを追加。

>ハッシュ化した password で認証ができるように設定
user モデルに has_secure_password を追加
ダミーデータの作成

ここらへんすでに完成してますよー

**Comment by yuki-tachi0219** [comment]
今回はログイン操作までは実装しないので、純粋に画面だけ表示させる感じですね。めちゃくちゃ速く終わりそうな予感がしてます。
