### ISSUE TITLE
ログイン、ログアウト処理

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#28]
ログイン: POST /login
ログアウト: DELETE /logout
ログイン後のリダイレクト先はユーザー詳細ページ
ログアウト後のリダイレクトはログインページ

ヘッダーにログアウトリンクを付けること

ログイン、ログアウト処理はHelperで定義すること。メソッド名はそれぞれlogin(user), logout

**Comment by naokinoid** [comment]
作業方針

- [ ] ルーティング（/login、/log_outを定義）

- [ ] コントローラー
　sessions_controllerを作成（create、destroyを定義）
　- create
　　sessions_helperにlogin(user)を定義
　　リダイレクト先はユーザー詳細ページ
　- destroy
　　sessions_helperにlogoutを定義
　　リダイレクト先はログインページ

- [ ] ルーティングの定義
　post   '/login'　→　sessions_controllerのcreateと紐付け
　delete '/logout'　→　sessions_controllerのdestroyと紐付け

- [ ] ログイン画面の実装
　- view/sessions/new.html.erbを作成
　　モックアップのsessions_new.htmlを移植
　- form_withメソッドを使ってログイン機能を実装
　　ルーティングのpost   '/login’と紐付け

- [ ] ログアウト処理の実装
　- ヘッダーのログアウトボタンとdelete '/logout'　を紐付け

**Comment by yuki-tachi0219** [comment]
問題ないので、そのまま進めていただければと思います。

**Comment by naokinoid** [comment]
@yuki-tachi0219 

ご確認ありがとうございます。
作業時間は3時間程度を見込んでいます。
