### ISSUE TITLE
認可処理機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#29]
ログインしていない場合、users#show, editページを見れないようにして自動的にログインページに遷移するよう、sessions_helper.rbに実装すること。
メソッド名はlogged_in_user
フラッシュメッセージは「ログインしてください。」

ログインしていたとしても、他人に関係するページは見れないようにして、自動的にroot_pathに遷移するよう、sessions_helper.rb に実装。
メソッド名はcorrect_user
フラッシュメッセージは「他人の情報にアクセスすることはできません。」

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by naokinoid** [comment]
## 方針

- ①ログインしていない場合にusers#show, editページを見れないようにして自動的にログインページに遷移
- [ ] sessions_helperにlogged_in_userを定義
- [ ] users_controllerのbefore_actionで logged_in_userを定義
　　対象メソッドはshow、edit


- ②ログインしていたとしても、他人に関係するページは見れないようにして、自動的にroot_pathに遷移する
- [ ] sessions_helperにcorrect_userを定義
- [ ] users_controllerのbefore_actionで correct_userを定義
　　対象メソッドはshow、edit

**Comment by yuki-tachi0219** [comment]
correct_userはヘルパーではなく、user_controllerで直接定義しましょう。
各コントローラにわたって共通化するのはけっこう難しいです。

**Comment by naokinoid** [comment]
@yuki-tachi0219 

実装完了いたしました。
スクリーンショット添付します。

※「他人の情報にアクセスすることはできません」のほうですが、
　レイアウトヘッダーと被っており、調整を試みています。

<img width="1440" alt="スクリーンショット 2021-08-30 22 57 00" src="https://user-images.githubusercontent.com/66786623/131351102-b4cd8a59-a6f6-4901-96e3-7b84e5476eef.png">

<img width="1440" alt="スクリーンショット 2021-08-30 22 57 17" src="https://user-images.githubusercontent.com/66786623/131351155-12b4fc04-e9ff-4408-b938-165603f5032f.png">

**Comment by yuki-tachi0219** [comment]
ログインしているときのヘッダの縦の高さが高いからですかねー

**Comment by naokinoid** [comment]
@yuki-tachi0219 

header に対して height: 10%;　を追加すると私の画面上では一旦解消しました。
本当はヘッダーの要素のすぐ下にアラートをくっつけるという指定の仕方がしたかったのですが
やり方がわからず時間もかかりそうで。。

一旦この状態でプルリクあげてもよろしでしょうか？

<img width="1440" alt="スクリーンショット 2021-08-30 23 37 15" src="https://user-images.githubusercontent.com/66786623/131356911-16c02372-9a59-4f91-b7fc-d19abb5ae769.png">
<img width="1440" alt="スクリーンショット 2021-08-30 23 37 18" src="https://user-images.githubusercontent.com/66786623/131356937-8cb04569-f1c9-4b04-933e-8c60a3696204.png">

**Comment by yuki-tachi0219** [comment]
OKです！
ヘッダーの下にくっつけるやり方は結構難しかった気がするので、このままいきましょう！
