### ISSUE TITLE
環境構築(かねゆきさん)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#3]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by e-kaneyuki** [comment]
<img width="1440" alt="スクリーンショット 2021-08-04 18 27 45" src="https://user-images.githubusercontent.com/69076028/128157545-6aece1a8-44fd-4452-8aa7-a50338bd9b74.png">

**Comment by yuki-tachi0219** [comment]
OKです！これで完了といたします！！
