### ISSUE TITLE
ページ遷移

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#30]
以下の画面遷移機能を実装すること
ヘッダーの商品検索をクリック→商品検索ページ(Products#index)
商品検索ページの各商品の右側の「商品詳細」ボタン→商品詳細ページ(Products#show)
ユーザー詳細ページの「修正/退会」ボタン→ユーザー修正ページ(Users#edit)

参考：https://pikawaka.com/rails/link_to#アプリ内でコードを書いてみよう

**Comment by miyagawadaiki515** [comment]
#30 ページ遷移　タスクチェックリスト

- [ ] ヘッダーの商品検索をクリック→商品検索ページ(Products#index) （実装済み）
- [ ] 商品検索ページの各商品の右側の「商品詳細」ボタン→商品詳細ページ(Products#show)　（実装済み）

- [ ] ユーザー詳細ページの「修正/退会」ボタン→ユーザー修正ページ(Users#edit)　← こちらだけ
- link_to メソッドを使って実装

- [ ] 動作確認

想定時間5分

**Comment by yuki-tachi0219** [comment]
注文履歴など、既に実装済みの画面へのリンクが貼られてないことがありそうなので、そちらも念の為ご確認お願いします。

**Comment by miyagawadaiki515** [comment]
現在僕が確認したところ、
・ユーザー詳細ページの「修正/退会」ボタン　→　ユーザー修正ページ(Users#edit)
に加えて
・ヘッダーの「新規登録」「カート」への遷移が実装されていませんでした。
カートページへの遷移の設定はいとうさんにお任せし、許可をいただきました。
また、新規登録ページへの遷移の設定の動作確認もしたいので、
#33 ユーザー登録ページ、登録処理　のタスクがマージされ取り込んだ後に、こちらのタスクのプルリクをあげようと考えています。
