### ISSUE TITLE
商品検索画面(検索ロジック以外)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#31]
path: /products
controller#action: Products#index
参考モックアップ: products_index.html(商品がある場合),products_index_not_found.html(商品がない場合)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

検索機能は除き、最初から全商品が表示されている状態にすること。
ページネーション機能は、kaminari gemを使うこと。
参考：https://qiita.com/d_nagano1002/items/fd90340c50324e845fe1
※Bootstrapの初期変更をしないようにしてください。できればスクショをIssueもしくはPR作成時に共有していただけると幸いです

ページネーションの表記を日本語で設定すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by naokinoid** [comment]
- [ ] ルーティング設定
  - Products#index
- [ ] コントローラーとアクションを定義
  - Productコントローラーのindexアクション
- [ ] モックアップからproducts/index.html.erbを作成
  - 件数取得
  - ページネーションの実装
  - 一覧表示
  - 商品詳細ページへの遷移
  - 商品０件の場合の分岐

**Comment by yuki-tachi0219** [comment]
いい感じだと思います！
ページネーション実装の際は、Poductコントローラーもいじることになりますので注意してください。

**Comment by naokinoid** [comment]
@yuki-tachi0219 

実装完了しました。

kaminariの日本語化ですが、指定のページの方法（kaminari_ja.ymlを生成）では上手くいかなかったため、
下記ページを参考にja.ymlの追加、application.rbへの追記で対応しましたが、問題ないかご確認お願いできますでしょうか？

https://qiita.com/tomo_k09/items/34702caa1202b8607206

<img width="1440" alt="スクリーンショット 2021-08-19 21 14 51" src="https://user-images.githubusercontent.com/66786623/130067177-cfa0df0d-cb18-48a6-a48b-d57c74ef9319.png">
<img width="1440" alt="スクリーンショット 2021-08-19 21 14 54" src="https://user-images.githubusercontent.com/66786623/130069759-b1a0917e-b3d6-4103-a86f-bf0055980577.png">
<img width="1440" alt="スクリーンショット 2021-08-19 21 38 03" src="https://user-images.githubusercontent.com/66786623/130069785-8b01263f-f9e4-4e61-bd78-4a569cb34f62.png">

**Comment by yuki-tachi0219** [comment]
OKです！やってることは参考サイトのものと実質同じはずなので、このままプルリクお願いします！
