### ISSUE TITLE
ユーザー登録ページ、登録処理

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#33]
登録ページ
path: GET /signup
controller#action: Users#new
参考モックアップ: sign_up.html

登録処理
path: POST /signup
controller#action: Users#create

登録後のリダイレクト先については画面定義書参照
登録に成功したら「ユーザーを登録しました。こちらからログインしてください。」というフラッシュメッセージを出すこと
登録に失敗したら、問題箇所を指摘するメッセージを表示すること。ユーザー修正画面と同様に実装すればOK

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

**Comment by miyagawadaiki515** [comment]
タスク手順チェックリスト
登録ページ
- [ ] users_controller に new アクションを追加
- [ ] GET /signup のルーティングを追加
- [ ] users/new.html.erb ファイルを作成(モックアップusers_new.html を参考)

登録処理
- [ ] users_controller に create アクションを追加
- [ ] POST /signup のルーティングを追加
- [ ] 登録の成功と失敗は、users/new.html.erb に if 文で、FrashHash インスタンスを使って判別し、フラッシュメッセージを表示（railsチュートリアル10章を参照）。登録成功後のリダイレクト先をログイン画面に設定。登録失敗後のエラーメッセージは、ユーザー情報更新のタスクのリンクを参照して考える。
- [ ] 画面定義書通りに実装ができたかを確認する

想定：5時間

**Comment by yuki-tachi0219** [comment]
いい感じです！そのままいきましょー
