### ISSUE TITLE
ヘッダー修正

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#34]
ログイン時、ログアウト時で表示を切り替えること
リンク先ページがあるものについてすべてリンクを有効にすること
ログイン時にヘッダーに名前を表示すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuki-tachi0219** [comment]
ProductsControllerのshowアクションで@userが定義されている場合の対応
↓
本来消せるはずなので消すこと。header.html.erbの名前を表示する箇所で`@user.first_name`としているのが原因。これをcurrent_user.first_nameとすればいい。
