### ISSUE TITLE
ユーザー退会

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#35]
path: DELETE /users/:id
controller#action: users#destroy
退会をボタンを押したら、
「ユーザーデータが全て削除されます。本当に退会しますか？」
というダイアログボックスが開くようにすること

退会後、トップページに遷移すること
自動的にログアウト状態になっているか確認すること。

**Comment by miyagawadaiki515** [comment]
#35 ユーザー退会　タスクチェックリスト
- [ ] users_controller に destroy メソッドを追加
- ユーザーを削除し、トップページへリダイレクトさせる
- [ ] users/edit.html.erb の退会ボタンに退会処理をつける
- link_to メソッドを使ってダイアログボックスを表示させる
- [ ] 実行できたらログアウト状態になっていることを確認。

想定時間：1時間

**Comment by yuki-tachi0219** [comment]
OKです！
