### ISSUE TITLE
商品検索画面(検索ロジック)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#36]
参考：https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2
商品の商品名カラムに対して部分一致の検索をかけること。
検索キーワードがないときは、全商品を表示させること。

**Comment by e-kaneyuki** [comment]
引用元：https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2
- [ ] 検索formの表示 
        - [ ] viewの確認・設定
- [ ] formにて検索ワードを入力(ユーザーが入力する)
- [ ] formから検索ワードを受け取る(Controller)
- [ ] Controller(とModelを使い)で、検索ワードを含むデータを出力。
- [ ] そのデータをViewに渡す。

**Comment by yuki-tachi0219** [comment]
引用元の記事に従えばできそうですね。
キーワードだけでなく、カテゴリーによる商品絞り込みも実装したいです。
