### ISSUE TITLE
注文履歴

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#37]
path: /orders
controller#action: Orders#index
参考モックアップ: order_history.html, order_index_not_found.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「直近3か月の注文を表示｣ボタンは実装しない
注文が存在しない場合の画面も、画面定義書参照のこと。

ページネーション機能は、kaminari gemを使うこと。

**Comment by naokinoid** [comment]
実装方針

- [ ] Contoller
- orders_controllerにindexアクションを定義

- [ ] View
- app/views/orders配下にindex.html.erbを作成
注文履歴が存在する場合/存在しない場合で分岐
- 履歴は注文日時降順でソート
- 「詳細」ボタン押下時、注文詳細画面へ遷移
- 備考欄　注文状態
１件でも注文状態が「準備中」のものがあれば「準備中」と表示
「準備中」の商品がなければ「発送済」と表示
has_prepared_shipment_statusメソッドを利用する
- ページネーションはkaminariを利用　１５件単位

**Comment by yuki-tachi0219** [comment]
いい感じです！そのまま進めていただければと思います 🐧
