### ISSUE TITLE
注文キャンセル

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#38]
注文詳細画面にて、注文をキャンセルするボタンを押したら該当する注文を削除する。
order_details も連動して削除されるかどうか確認すること。
注文がキャンセルされたら、注文履歴ページに遷移させること

**Comment by miyagawadaiki515** [comment]
#38 注文キャンセル　タスクチェックリスト
- [ ] ルーティングは設定済み
- [ ] orders_controller にdestroy メソッドを追加し、find_by メソッドで order の id を取得する。
- [ ] orders/show.html.erb の「注文をキャンセルする」ボタンを link_to メソッドを用いて書く。リンク先は注文履歴ページ。メソッドは destroy を定義する。
- [ ] order と order_detail が削除されることを確認（order モデルで order_detail の destroy に関しては外部キー制約を外しているので一緒に削除されるはず）。

所要時間30分

**Comment by yuki-tachi0219** [comment]
OKです！
