### ISSUE TITLE
カート機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#39]
カートページ
path: POST carts/add_cart
controller#action: carts#show,
参考モックアップ: cart_list.html

削除処理
path: DELETE carts/destroy
controller#action: Users#create

カートへ商品を追加、削除する機能を実装。

注文確定のボタン押下後、注文情報をDBへ格納し、購入画面へ遷移

sessionを使用した実装にすること。

**Comment by naokinoid** [comment]
## 実装方針

- [ ] カートデータの管理
sessionを利用する
カートのデータを配列でセットしていく
カートのデータそれぞれはハッシュで保持（キーはproduct_id、quantity）
　　　

- [ ] CartControllerの作成
- index：カート一覧画面を渡す
カートに何もなければ空の配列を、あればカートの中身をviewに渡す
- create：カートに商品を追加
既に追加済みの商品であれば数量を加算
新規の商品であれば商品ID、数量をハッシュでまとめてカートの配列にpush

- destroy：カートの商品を削除

- confirm：カート内のデータで注文を確定（order、order_detailの作成）、カートの中身をクリア

- [ ] View

- カート一覧
app/views/carts/index.html.erb を作成
モックアップ（carts_show.html）を移植
商品名やカテゴリー名、料金等の取得メソッドをCartsHelper.rbに定義する
（CartContollerからは商品IDと数量しか渡さない）

- カートへの追加
app/views/product/show.html.erbの「カートへ」を押下した際に追加
CartController#createを呼び出す
form_withを利用して商品ID、数量をpostする
商品IDはhiddenにしておく

- カートの削除
カート一覧画面の「削除」ボタンを押下すると削除
CartController#destroyを呼び出す

- カートの確定
カート一覧画面で「注文を確定する」ボタンを押すと確定
CartController#confirmを呼び出す

- [ ] 想定工数：8時間

**Comment by yuki-tachi0219** [comment]
>confirm：カート内のデータで注文を確定（order、order_detailの作成）、カートの中身をクリア

これはOrders#create アクションで行いましょう

**Comment by yuki-tachi0219** [comment]
カートない商品の数量変更アクションが必要ですね。
Cart#change_quantity みたいなアクションにしましょうか。

**Comment by yuki-tachi0219** [comment]
>カート一覧画面の「削除」ボタンを押下すると削除

たしか商品1種類ずつ消すアクションだったと思うので、そこらへんお間違えのないように気をつけてください。
どの商品を消すかという情報をparamsに入れる必要がありそうですね

**Comment by naokinoid** [comment]
@yuki-tachi0219 

ご指摘ありがとうございます。

数量変更、画面定義書の記載を見落としていました。

「フォーカスアウト時、小計、合計を再計算」とありますが、
これはAjaxを使っての実装になるのでしょうか？

**Comment by yuki-tachi0219** [comment]
Ajaxを使わないといけないですが、これは難しいので今回は実装しなくて大丈夫です

**Comment by naokinoid** [comment]
@yuki-tachi0219 

了解しました！
ご確認ありがとうございます。
