### ISSUE TITLE
環境構築(いとうさん)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#4]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by naokinoid** [comment]
@yuki-tachi0219 

docker起動し、http://localhost:3000で「Yeh! You're on Rails!!」表示されました。
![Uploading スクリーンショット 2021-08-03 18.34.47.png…]()

**Comment by yuki-tachi0219** [comment]
画像を貼っていただいているように見えますが、画像が見えないですね

**Comment by naokinoid** [comment]
申し訳ありません、上手くいっていなかったようです。
下記でいかがでしょうか？

<img width="1373" alt="スクリーンショット 2021-08-03 18 34 47" src="https://user-images.githubusercontent.com/66786623/128013007-2d1d143f-1c95-4379-be9a-801b08a4d50d.png">

**Comment by naokinoid** [comment]
> 画像を貼っていただいているように見えますが、画像が見えないですね

**Comment by naokinoid** [comment]
申し訳ありません、謝ってcloseをしてしまいました。
reopenしました。

**Comment by yuki-tachi0219** [comment]
確認できました！
これで完了といたします！
