### ISSUE TITLE
DB構築 Migration Users関連

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#8]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
対象はUserとUserClassificationの2モデル。
DB構造は、GoogleドライブのER図を参考にすること

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のUserに関する部分をスクショして添付すること

**Comment by naokinoid** [comment]
@yuki-tachi0219 

db/schema.rbのスクショ添付します。
ご確認お願いします。
<img width="829" alt="スクリーンショット 2021-08-05 8 14 22" src="https://user-images.githubusercontent.com/66786623/128267404-e3976177-5736-4f41-8b3d-ee538d17242b.png">

**Comment by yuki-tachi0219** [comment]
ありがとうございます。よさそうなのでそのままプルリクしていただければと思います。
