### ISSUE TITLE
DB構築 Migration Products関連

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-lily#9]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること
対象はProducts関連の合計5テーブル。

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のProductに関する部分をスクショして添付すること

**Comment by e-kaneyuki** [comment]
@yuki-tachi0219

## 5つのテーブル作成を行いました
### db/schema.rbのスクショ添付します
### ご確認お願いします

- products
- product_statuses
- categories
- purchases
- sale_statuses

<img width="1261" alt="スクリーンショット 2021-08-06 23 19 48" src="https://user-images.githubusercontent.com/69076028/128524700-8c9e767d-ce74-4592-985e-662c8809eaa5.png">
<img width="1269" alt="スクリーンショット 2021-08-06 23 22 59" src="https://user-images.githubusercontent.com/69076028/128524852-2fa61d43-a8de-4d92-b77b-ec0b970787b3.png">

**Comment by shohheyhey** [comment]
@e-kaneyuki
めっちゃいい感じですね！👍
気になったところ述べますね！
- products テーブル
  - description は tiny で OK? varchar(256) なので text なのでは？
  - sale_status_id, product_status_id, category_id は null: false の方がよさそう
- purchases テーブル
  - product_id は null: false の方がよさそう

以上です！
@yuki-tachi0219 
ご確認お願いします🙏

**Comment by e-kaneyuki** [comment]
@shohheyhey 
レビューありがとうございます！
ご指摘のあった箇所の修正対応しました
ご確認お願いいたします😄

> • products テーブル
   • description は tiny で OK? varchar(256) なので text なのでは？
   • sale_status_id, product_status_id, category_id は null: false の方がよさそう
• purchases テーブル
   • product_id は null: false の方がよさそう

<img width="816" alt="スクリーンショット 2021-08-07 13 15 33" src="https://user-images.githubusercontent.com/69076028/128587706-ba07d1aa-6cab-46e6-903d-4b6148fa452d.png">
<img width="882" alt="スクリーンショット 2021-08-07 13 19 52" src="https://user-images.githubusercontent.com/69076028/128587713-aac5f329-7a4b-4d8f-8a29-71c978b198f7.png">
